import type { Metadata } from "next";
import "./globals.css";
import SessionProviderWrapper from "@/lib/SessionProviderWrapper"
export const metadata: Metadata = {
  title: "Your App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className="dark">
          <SessionProviderWrapper>
            {children}
          </SessionProviderWrapper>
        </body>
      </html>
  );
}
