import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/auth-components/SessionWrapper";

export const metadata: Metadata = {
  title: "Your App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="dark">
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
